<?php
/**
 * Ffuenf_BankPayment extension.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category   Ffuenf
 *
 * @author     Achim Rosenhagen <a.rosenhagen@ffuenf.de>
 * @copyright  Copyright (c) 2015 ffuenf (http://www.ffuenf.de)
 * @license    http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<?php $quoteCurrencyCode = $this->getQuoteCurrencyCode(); ?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode(); ?>" style="display:none">
        <li>
        <?php if ($_cmsPage = $this->getFormCmsUrl()): ?>
            <div class="input-box">
                <p><?php echo $this->__('More information on this paymentmethod can be found <a target="_blank" href="%s">here</a>.', $_cmsPage) ?></p>
            </div>
        <?php elseif ($_accounts = $this->getAccounts()): ?>
            <?php $first = true; ?>
            <?php foreach($_accounts as $_account): ?>
                <?php if ($quoteCurrencyCode != '' && in_array($quoteCurrencyCode, $_account->getCurrencies())): ?>
                    <?php if ($this->getMethod()->getPayWithinXDays() > 0): ?>
                        <?php echo $this->__('Please transfer the money within %s days to the following bank account', $this->getMethod()->getPayWithinXDays()); ?>:
                    <?php else: ?>
                        <?php echo $this->__('Please transfer the money to the following bank account'); ?>:
                    <?php endif; ?>
                    <br /><br />
                    <div class="input-box">
                        <?php if (!$first): ?>
                        <br /><hr/><br />
                        <?php endif; $first = false; ?>
                        <table>
                            <tbody>
                                <?php if ($_accountHolder = $_account->getAccountHolder()): ?>
                                    <tr><td><label><?php echo $this->__('Account holder') ?></label>: </td><td><?php echo $_accountHolder ?></td></tr>
                                <?php endif; ?>
                                <?php if ($_bankName = $_account->getBankName()): ?>
                                    <tr><td><label><?php echo $this->__('Bank name') ?></label>: </td><td><?php echo $_bankName ?></td></tr>
                                <?php endif; ?>
                                <?php if ($_iban = $_account->getIban()): ?>
                                    <tr><td><label><?php echo $this->__('IBAN') ?></label>: </td><td><?php echo $_iban ?></td></tr>
                                <?php endif; ?>
                                <?php if ($_bic = $_account->getBic()): ?>
                                    <tr><td><label><?php echo $this->__('BIC') ?></label>: </td><td><?php echo $_bic ?></td></tr>
                                <?php endif; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($_customText = $this->getMethod()->getCustomText()): ?>
                <br />
                <?php echo $_customText ?><br />
            <?php endif; ?>
        <?php endif; ?>
        </li>
    </ul>
</fieldset>