<?php
/**
 * Ffuenf_BankPayment extension.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/mit-license.php
 *
 * @category   Ffuenf
 *
 * @author     Achim Rosenhagen <a.rosenhagen@ffuenf.de>
 * @copyright  Copyright (c) 2015 ffuenf (http://www.ffuenf.de)
 * @license    http://opensource.org/licenses/mit-license.php MIT License
 */
?>
<p>
    <?php echo $this->getMethod()->getTitle(); ?> - <span style="font-style:italic;"><?php echo $this->__('Account info'); ?></span><br />
    <?php $_accounts = $this->getAccounts(); ?>
    <?php foreach($_accounts as $_account): ?>
    <br />
    <table class="bankpayment_info">
        <tbody>
        <?php if ($_accountHolder = $_account->getAccountHolder()): ?>
            <tr>
                <td class="bankcol1"><label><?php echo $this->__('Account holder') ?></label>: </td>
                <td class="bankcol2"><?php echo $_accountHolder ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($_bankName = $_account->getBankName()): ?>
            <tr>
                <td class="bankcol1"><label><?php echo $this->__('Bank name') ?></label>: </td>
                <td class="bankcol2"><?php echo $_bankName ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($_iban = $_account->getIban()): ?>
            <tr>
                <td class="bankcol1"><label><?php echo $this->__('IBAN') ?></label>: </td>
                <td class="bankcol2"><?php echo $_iban ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($_bic = $_account->getBic()): ?>
            <tr>
                <td class="bankcol1"><label><?php echo $this->__('BIC') ?></label>: </td>
                <td class="bankcol2"><?php echo $_bic ?></td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
    <?php endforeach; ?>
    <?php if ($_customText = $this->getMethod()->getCustomText()): ?>
        <br />
        <?php echo $_customText; ?><br />
    <?php endif; ?>
</p>
